#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=5

banner "Base ZK Credits: founder's internal x402 demo"

stage "Confirm the demo is internal and uncounted"
say "Run this before invitations or the hosted external pilot. This is an"
say "internal Base Sepolia check and never counts as slot B or activation evidence."
say "The demo sends one billable request using founder-provisioned test credits."
say "The task and response stay in the local terminal; record only the redacted"
say "status and closed aggregate checks."
if ! confirm "Are you the founder, using your own credential and approving one internal test-credit spend?"; then
  warn "stop here; this demo is founder-only"
  exit 1
fi

stage "Install the reviewed candidate and import locally"
say "Follow docs/onboarding/base-zk-credits-founder-demo.md from the repo root."
say "Verify the reviewed 0.2.9 tarball with its SHA256SUMS, then install it in"
say "a private directory outside the checkout. Do not substitute registry 0.2.8."
say "The candidate packages its pinned proving bundle; private repository access"
say "and a credential password are not required for new version-3 imports."
say "Obtain your founder-funded activated credential through website onboarding."
say "Keep the bearer file private; import it with the candidate's setup x402."
say "Use the same ZK_CREDITS_HOME for setup and the demo; OS storage may prompt."
say "Public Base Sepolia RPC is the default; config rpc sets a private override."
say "Stop if setup cannot confirm the gateway root. The release handover records"
say "an unresolved hosted root gate; a failed setup is not successful readiness."
if ! confirm "Has candidate setup verified artifacts, OS credential access, witness, and gateway-known root?"; then
  warn "finish setup or record a blocked run without sending a task"
  exit 1
fi

stage "Run one custom task through the founder x402 agent"
say "The command asks for the task in this terminal and then requires an"
say "explicit confirmation. It displays the model response locally and prints"
say "only exchange phases and aggregate counter deltas in its status summary."
step "In the fresh candidate installation run: ./node_modules/.bin/zk-credits founder-demo-agent"
say "Stop any running sidecar first. Keep the gateway quiet so aggregate deltas"
say "can be checked. The command prompts for the admin token with hidden input."
step "Enter your task in the local prompt. Do not put secrets or participant data in it."
step "At the explicit confirmation, approve one internal exchange only."
pause "Press Enter after the command has completed or stopped with a status."

stage "Redact before retaining or sharing"
warn "Do not record the task terminal: it displays your task and model response."
say "Do not tee, redirect, or save the full terminal transcript or take a screenshot."
say "If a recording already exists, redact request/response content, bearer files,"
say "tokens, proofs, nullifiers, request signals, identities, and endpoint keys"
say "locally before retaining or sharing it. Review every frame and audio track."
say "Prefer the fixed-shape record below; do not append arbitrary log excerpts."
if ! confirm "Have you reviewed the material and excluded all private content before retention or sharing?"; then
  warn "stop; review and redact locally before creating the record"
  exit 1
fi

stage "Write a safe local record and check the official funding route"
say 'The funding target is a $5,000 Base Builder Grant. Open the Builder Grant'
say "application and verify the current round, amount, submission route, and"
say "testnet prototype eligibility before preparing or submitting materials."
open_url "https://docs.google.com/forms/d/e/1FAIpQLSeEFi9BLm5XCm7KrFzRZC-rxcAqCNZPzWZ9He4aZkxsKuRXjw/viewform"
pause "Press Enter after checking the official route and eligibility."
while true; do
  ask DEMO_OUTCOME "Demo outcome (succeeded, blocked, or failed):"
  case "$DEMO_OUTCOME" in succeeded|blocked|failed) break ;; *) warn "choose succeeded, blocked, or failed" ;; esac
done
while true; do
  ask DEMO_EXCHANGE_CHECK "Did the output show local proof self-check, PAYMENT-SIGNATURE, facilitator settlement, PAYMENT-RESPONSE, and the expected aggregate gateway delta? (yes/no):"
  case "$DEMO_EXCHANGE_CHECK" in yes|no) break ;; *) warn "answer yes or no" ;; esac
done
while true; do
  ask DEMO_GRANT_ROUTE "Base Builder Grant fit (potential-fit, not-a-fit, or needs-review):"
  case "$DEMO_GRANT_ROUTE" in potential-fit|not-a-fit|needs-review) break ;; *) warn "choose one listed status" ;; esac
done
note "On 2026-09-30, the Coinbase-created Builder Grant application says Round 1"
note "is closed; watch X for Round 2. Recheck status and eligibility before"
note "submission. The target amount is not a verified award or entitlement."
if [[ "$DEMO_OUTCOME" == succeeded && "$DEMO_EXCHANGE_CHECK" != yes ]]; then
  warn "a successful demo requires every exchange check; recording this as blocked"
  DEMO_OUTCOME=blocked
fi
umask 077
DEMO_RECORD_DIR="${ZK_CREDITS_DEMO_RECORD_DIR:-$HOME/.zk-credits/demo-records}"
mkdir -p "$DEMO_RECORD_DIR"
chmod 700 "$DEMO_RECORD_DIR"
DEMO_RECORD="$DEMO_RECORD_DIR/founder-demo-$(date -u +%Y-%m-%dT%H-%M-%SZ).md"
cat > "$DEMO_RECORD" <<EOF
# Founder Base Sepolia x402 demo

- Date (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)
- Package candidate: zk-credits 0.2.9; adapter 0.1.0; shared 0.1.0
- Network: Base Sepolia (eip155:84532)
- Internal demo: yes
- Counted as slot B: no
- Counted as an external activation: no
- Starts the 14-day window: no
- Funding application submitted by this wizard: no
- Demo outcome: $DEMO_OUTCOME
- Required exchange checks reported: $DEMO_EXCHANGE_CHECK
- Funding target: \$5,000 Base Builder Grant
- Base Builder Grant fit: $DEMO_GRANT_ROUTE
- Builder Grant application: https://docs.google.com/forms/d/e/1FAIpQLSeEFi9BLm5XCm7KrFzRZC-rxcAqCNZPzWZ9He4aZkxsKuRXjw/viewform
- Route check baseline: 2026-09-30; Round 1 closed; watch X for Round 2
- Target amount is not a verified award or entitlement

No participant was involved. This file excludes the task, model response,
credential, passwords, admin token, proofs, nullifiers, request signals,
identities, and spend-plane joins.
EOF
chmod 600 "$DEMO_RECORD"
printf '  %s✓%s wrote redacted local record %s\n' "$GREEN" "$RESET" "$DEMO_RECORD"
say "Keep this record separate from activation evidence. After A qualifies,"
say "slot B requires a fresh measured run; this demo never substitutes for it."
say "Keep the task, response, and credentials out of the record. Prepare funding"
say "materials privately and state only what the demo verified and what Base's"
say "official route actually accepts."

finish
