#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${ZK_CREDITS_LAUNCH_ENV:-.env.launch.local}"
WIZARD_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=scripts/launch-guardrails.sh
source "$WIZARD_DIR/launch-guardrails.sh"

# Keys this wizard owns. `gw_refuse_stray_keys` rejects anything else that is
# already in the file, so an operator or personal value cannot ride along.
#
# The list is the whole founder plane, not just the values captured below:
# scripts/launch-pilot.sh reads the same file, so the keys it owns have to be
# acceptable here or the two entrypoints would disagree about one file.
LAUNCH_KEYS=(
  BASE_RPC_URL BASE_USDC_ADDRESS BASE_DEPLOYMENT_DOMAIN
  BASE_DEPLOYER_KEYSTORE_ACCOUNT BASE_DEPLOYER_PASSWORD_FILE
  BASE_SPONSOR_PRIVATE_KEY BASE_SPONSOR_ADDRESS BASE_TREASURY_ADDRESS
  BASE_REFUND_VAULT BASE_SPEND_VERIFIER_ADDRESS BASE_POSEIDON_T2_ADDRESS
  BASE_POSEIDON_T3_ADDRESS BASE_POSEIDON_T4_ADDRESS BASE_BOND_ADDRESS
  BASE_BOND_DEPLOYMENT_BLOCK BASE_CONFIRMATIONS
  BASE_PRIVATE_CREDIT_BOND_ADDRESS BASE_DEPLOYMENT_BLOCK
  DATABASE_URL PUBLIC_GATEWAY_URL
  BILLING_INTERNAL_TOKEN FACILITATOR_SERVICE_TOKEN CLAIM_STORE_OPERATOR_TOKEN
  OPENROUTER_API_KEY GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET NEXTAUTH_SECRET
  NEXTAUTH_URL GATEWAY_URL
  NPM_TOKEN BASESCAN_API_KEY
  NEON_API_KEY RENDER_API_KEY RENDER_OWNER_ID VERCEL_TOKEN
  PILOT_ENVIRONMENT PILOT_REPO PILOT_BRANCH
  PILOT_OPERATOR_A_GITHUB_ID PILOT_OPERATOR_B_GITHUB_ID PILOT_OPERATOR_C_GITHUB_ID
  PILOT_STAGING_DAILY_CAP_MICRO_USD PILOT_STAGING_ROLLING_CAP_MICRO_USD
  PILOT_RELEASE_REVIEWED
)

# ask_validated KEY "Prompt" VALIDATOR "Label" repeats until the value holds.
ask_validated() {
  local key="$1" prompt="$2" validator="$3" label="$4" value
  while true; do
    ask "$key" "$prompt"
    value="${!key}"
    if "$validator" "$value" "$label"; then return 0; fi
    warn "try again"
  done
}

ask_validated_secret() {
  local key="$1" prompt="$2" validator="$3" label="$4" value
  while true; do
    ask_secret "$key" "$prompt"
    value="${!key}"
    if "$validator" "$value" "$label"; then return 0; fi
    warn "try again"
  done
}

TOTAL_STAGES=9

BASE_SEPOLIA_USDC_ADDRESS='0x036CbD53842c5426634e7929541eC2318f3dCF7e'
BASE_REVIEWED_SPEND_VERIFIER_ADDRESS='0xD3FED81c5Aa3D1c976448cAaDAa66832E7F5BCDD'

banner "Founder launch: Base Sepolia pilot infrastructure"

# ── Stage 1: preconditions ────────────────────────────────────────────────
stage "Preconditions: the launch env is founder-only"
say "This wizard writes infrastructure secrets to $ENV_FILE."
note "Operator keys, credential secrets, and operator env files belong on each"
note "operator's own machine in .env.operator.local, never here."
if ! gw_refuse_operator_vars; then
  warn "unset those variables and re-run"; exit 1
fi
if ! gw_require_ignored "$ENV_FILE"; then exit 1; fi
if ! gw_require_private_mode "$ENV_FILE"; then exit 1; fi
if ! gw_refuse_stray_keys "$ENV_FILE" "${LAUNCH_KEYS[@]}"; then exit 1; fi
printf '  %s✓%s %s is ignored and mode 600\n' "$GREEN" "$RESET" "$ENV_FILE"
note "Nothing on this machine may log a secret: the wizard prints key names only."

# ── Stage 2: Base Sepolia RPC and deployment identity ─────────────────────
stage "Base Sepolia: dedicated RPC and deployment identity"
say "The gateway and the sidecar both read the chain through a dedicated RPC."
note "The shared public endpoint is rate-limited and must not be used for the pilot."
open_url "https://dashboard.alchemy.com/apps"
step "Create or open a Base Sepolia app, then copy its HTTPS endpoint."
while true; do
  ask BASE_RPC_URL "Paste the dedicated Base Sepolia RPC URL:"
  if gw_require_match "$BASE_RPC_URL" '^https://[^[:space:]]+$' "BASE_RPC_URL"; then
    if [[ "$BASE_RPC_URL" == *'sepolia.base.org'* ]]; then
      warn "that is the shared public endpoint; use the dedicated Alchemy URL"
    else
      break
    fi
  fi
  warn "try again"
done
write_env BASE_RPC_URL "$BASE_RPC_URL"

ask BASE_DEPLOYMENT_DOMAIN "Deployment domain (84532 for Base Sepolia):"
if ! gw_require_match "$BASE_DEPLOYMENT_DOMAIN" '^84532$' "BASE_DEPLOYMENT_DOMAIN"; then
  warn "the pilot is Base Sepolia only"; exit 1
fi
write_env BASE_DEPLOYMENT_DOMAIN "$BASE_DEPLOYMENT_DOMAIN"

ask BASE_USDC_ADDRESS "Base Sepolia USDC address [Enter uses Circle's official address]:"
if [[ -z "$BASE_USDC_ADDRESS" ]]; then BASE_USDC_ADDRESS="$BASE_SEPOLIA_USDC_ADDRESS"; fi
if ! gw_require_address "$BASE_USDC_ADDRESS" "BASE_USDC_ADDRESS"; then exit 1; fi
write_env BASE_USDC_ADDRESS "$BASE_USDC_ADDRESS"

ask BASE_DEPLOYER_KEYSTORE_ACCOUNT "Foundry deployer account name (not a private key):"
if ! gw_require_match "$BASE_DEPLOYER_KEYSTORE_ACCOUNT" '^[A-Za-z_][A-Za-z0-9_-]*$' "BASE_DEPLOYER_KEYSTORE_ACCOUNT"; then exit 1; fi
write_env BASE_DEPLOYER_KEYSTORE_ACCOUNT "$BASE_DEPLOYER_KEYSTORE_ACCOUNT"

ask BASE_DEPLOYER_PASSWORD_FILE "Absolute path to the Foundry keystore password file (mode 600):"
if ! gw_require_password_file "$BASE_DEPLOYER_PASSWORD_FILE" "BASE_DEPLOYER_PASSWORD_FILE"; then exit 1; fi
write_env BASE_DEPLOYER_PASSWORD_FILE "$BASE_DEPLOYER_PASSWORD_FILE"

write_env BASE_SPEND_VERIFIER_ADDRESS "$BASE_REVIEWED_SPEND_VERIFIER_ADDRESS"
note "The reviewed SpendVerifier adapter is fixed at $BASE_REVIEWED_SPEND_VERIFIER_ADDRESS."
note "The launcher verifies that it wraps the reviewed verifier before deployment."

ask_secret BASESCAN_API_KEY "Optional BaseScan API key (Enter to defer verification):"
if [[ -n "$BASESCAN_API_KEY" ]]; then
  if ! gw_require_secret "$BASESCAN_API_KEY" "BASESCAN_API_KEY"; then exit 1; fi
  write_env BASESCAN_API_KEY "$BASESCAN_API_KEY"
fi

# ── Stage 3: sponsor key and payout addresses ─────────────────────────────
stage "Base Sepolia: sponsor hot key and payout addresses"
say "The sponsor key funds the USDC bond for each pilot credential."
note "Use a separate hot key funded with a bounded pilot amount only."
note "The refund/treasury vault is configured by address. Its private key is"
note "never entered here and never handed to a deployment script."
ask_validated_secret BASE_SPONSOR_PRIVATE_KEY "Paste the sponsor hot key:" gw_require_private_key "BASE_SPONSOR_PRIVATE_KEY"
write_env BASE_SPONSOR_PRIVATE_KEY "$BASE_SPONSOR_PRIVATE_KEY"

ask BASE_TREASURY_ADDRESS "Treasury address that receives settled credit (0x…):"
if ! gw_require_address "$BASE_TREASURY_ADDRESS" "BASE_TREASURY_ADDRESS"; then exit 1; fi
write_env BASE_TREASURY_ADDRESS "$BASE_TREASURY_ADDRESS"

ask BASE_REFUND_VAULT "Offline refund vault address (0x…, address only):"
if ! gw_require_address "$BASE_REFUND_VAULT" "BASE_REFUND_VAULT"; then exit 1; fi
write_env BASE_REFUND_VAULT "$BASE_REFUND_VAULT"
note "Confirm the vault key is offline. This wizard cannot and will not hold it."

# ── Stage 4: Neon Postgres ────────────────────────────────────────────────
stage "Postgres: Neon free, direct TLS, Singapore"
say "The durable claim store and launch controls live in Neon."
open_url "https://console.neon.tech"
step "Open the project, then Connection details."
step "Pick the Singapore region and the DIRECT connection (no '-pooler' host)."
step "Copy the whole postgresql:// connection string, TLS parameters included."
while true; do
  ask_secret DATABASE_URL "Paste the Neon direct connection string:"
  if gw_require_direct_postgres "$DATABASE_URL" "DATABASE_URL"; then break; fi
  warn "try again"
done
write_env DATABASE_URL "$DATABASE_URL"
note "Render must not declare a database: DATABASE_URL is set in the dashboard."

# ── Stage 5: Render gateway ───────────────────────────────────────────────
stage "Render: free gateway service and its service tokens"
say "The blueprint runs the gateway on the free plan in Singapore."
note "A free instance suspends, so activation prewarms /health before inviting."
open_url "https://dashboard.render.com"
step "Create a Blueprint from this repository so render.yaml is applied."
step "Set every 'sync: false' value in the dashboard."
step "Once it is live, copy the service URL."
while true; do
  ask PUBLIC_GATEWAY_URL "Paste the gateway base URL (https://…):"
  if gw_require_https_url "$PUBLIC_GATEWAY_URL" "PUBLIC_GATEWAY_URL"; then break; fi
  warn "try again"
done
write_env PUBLIC_GATEWAY_URL "$PUBLIC_GATEWAY_URL"

say "Now three independent service tokens. Generate each one with:"
note "  openssl rand -base64 48"
ask_validated_secret BILLING_INTERNAL_TOKEN "Paste BILLING_INTERNAL_TOKEN:" gw_require_secret "BILLING_INTERNAL_TOKEN"
write_env BILLING_INTERNAL_TOKEN "$BILLING_INTERNAL_TOKEN"
ask_validated_secret FACILITATOR_SERVICE_TOKEN "Paste FACILITATOR_SERVICE_TOKEN:" gw_require_secret "FACILITATOR_SERVICE_TOKEN"
write_env FACILITATOR_SERVICE_TOKEN "$FACILITATOR_SERVICE_TOKEN"
ask_validated_secret CLAIM_STORE_OPERATOR_TOKEN "Paste CLAIM_STORE_OPERATOR_TOKEN:" gw_require_secret "CLAIM_STORE_OPERATOR_TOKEN"
write_env CLAIM_STORE_OPERATOR_TOKEN "$CLAIM_STORE_OPERATOR_TOKEN"
note "Each token must be distinct or the planes are not separated."
if [[ "$BILLING_INTERNAL_TOKEN" == "$FACILITATOR_SERVICE_TOKEN" || "$BILLING_INTERNAL_TOKEN" == "$CLAIM_STORE_OPERATOR_TOKEN" || "$FACILITATOR_SERVICE_TOKEN" == "$CLAIM_STORE_OPERATOR_TOKEN" ]]; then
  warn "the three service tokens are not distinct"; exit 1
fi

# ── Stage 6: upstream provider ────────────────────────────────────────────
stage "Upstream provider: OpenRouter"
say "One credit buys one committed response from the fixed service class."
open_url "https://openrouter.ai/keys"
step "Create a key scoped to the pilot, with its own spend limit."
ask_validated_secret OPENROUTER_API_KEY "Paste the OpenRouter key:" gw_require_secret "OPENROUTER_API_KEY"
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
note "The gateway caps provider spend at \$40 per UTC day and \$200 per 30 days."

# ── Stage 7: Vercel web and GitHub OAuth ──────────────────────────────────
stage "Vercel web: GitHub OAuth sign-in"
say "The web app is sign-in only. Checkout, Stripe, and wallet linking are gone."
open_url "https://github.com/settings/developers"
step "New OAuth App. Callback: https://<your-web-host>/api/auth/callback/github"
ask GITHUB_CLIENT_ID "Paste the OAuth client id:"
if ! gw_require_match "$GITHUB_CLIENT_ID" '^[A-Za-z0-9._-]{8,}$' "GITHUB_CLIENT_ID"; then exit 1; fi
write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"
ask_validated_secret GITHUB_CLIENT_SECRET "Paste the OAuth client secret:" gw_require_secret "GITHUB_CLIENT_SECRET"
write_env GITHUB_CLIENT_SECRET "$GITHUB_CLIENT_SECRET"

say "Next, the NextAuth secret and the two URLs."
note "  openssl rand -base64 32"
ask_validated_secret NEXTAUTH_SECRET "Paste NEXTAUTH_SECRET:" gw_require_secret "NEXTAUTH_SECRET"
write_env NEXTAUTH_SECRET "$NEXTAUTH_SECRET"

open_url "https://vercel.com/new"
step "Import this repository, then copy the production deployment URL."
while true; do
  ask NEXTAUTH_URL "Paste the web base URL (https://…):"
  if gw_require_https_url "$NEXTAUTH_URL" "NEXTAUTH_URL"; then break; fi
  warn "try again"
done
write_env NEXTAUTH_URL "$NEXTAUTH_URL"
write_env GATEWAY_URL "$PUBLIC_GATEWAY_URL"
note "Do not enable ENABLE_DEV_LOGIN, Stripe, or any legacy Stellar route there."

# ── Stage 8: CI wiring ────────────────────────────────────────────────────
stage "CI: defer provider wiring until deployment outputs exist"
say "This wizard is configuration-only. It does not create provider resources"
say "or write GitHub variables, and it never broadcasts a contract."
note "After launch-pilot reconciles all four contracts, it atomically writes"
note "the bond address, deployment block, sponsor address, and confirmations."
note "Only then may hosting, GitHub-variable, and pilot-activation stages proceed."

# ── Stage 9: checkpointed launcher handoff ─────────────────────────────────
stage "Checkpointed launcher handoff"
say "The pre-deployment values are captured safely in $ENV_FILE."
note "Run the read-only checks first:"
note "  scripts/launch-pilot.sh --check"
note "Then run the launcher. It simulates, summarizes nonsecret inputs, and"
note "requires a fresh explicit confirmation before showing the keystore command."
note "No deployment command is executed by this wizard."
finish
