#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
ENV_FILE="${ZK_CREDITS_OPERATOR_ENV:-.env.operator.local}"
WIZARD_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
if [[ -f "$WIZARD_DIR/launch-guardrails.sh" ]]; then
  # shellcheck source=scripts/launch-guardrails.sh
  source "$WIZARD_DIR/launch-guardrails.sh"
else
  printf 'Keep launch-guardrails.sh beside this wizard; it is delivered together.\n' >&2
  exit 1
fi

PINNED_SIDECAR_VERSION='0.2.7'
PINNED_ADAPTER_VERSION='0.1.0'
PINNED_SHARED_VERSION='0.1.0'
PINNED_ARTIFACT_RELEASE='private-credit-spend-bn254-dev-sepolia-v2'
OPERATOR_HOME="${ZK_CREDITS_HOME:-$HOME/.zk-credits}"
TOKEN_PATH="$OPERATOR_HOME/loopback-token"
SLOT=''
PARTICIPANT_TYPE=''
INTEGRATION_MODE=''
ASSISTANCE=0

sidecar_metrics_json() {
  local token
  [[ -f "$TOKEN_PATH" ]] || return 1
  token=$(cat "$TOKEN_PATH")
  curl -fsS --max-time 15 -H "Authorization: Bearer $token" \
    "http://127.0.0.1:${ZK_CREDITS_SIDECAR_PORT:-3210}/metrics"
}

slot_participant_type() { case "$1" in A) printf 'coding_agent' ;; B|C) printf 'x402_native_agent' ;; *) return 1 ;; esac; }
slot_integration_mode() { case "$1" in A) printf 'openai_compatible_sidecar' ;; B|C) printf 'x402_zk_prepaid_adapter' ;; *) return 1 ;; esac; }

TOTAL_STAGES=5
banner "Base ZK Credits: first-use activation"

stage "Consent and your assigned slot"
say "A is an external Codex developer; B is the founder using the starter"
say "x402 agent; C is an external x402 operator integrating their own agent."
say "Only A and C count toward market validation. B is a technical activation."
say "External A and C receive $25 for a 30-minute research session, whether"
say "setup succeeds or fails. That honorarium is not product revenue or intent."
while true; do
  ask SLOT "Your assigned slot (A, B, or C):"
  SLOT=$(printf '%s' "${SLOT:-}" | tr '[:lower:]' '[:upper:]')
  if [[ "$SLOT" =~ ^[ABC]$ ]]; then break; fi
  warn "the slot must be A, B, or C"
done
PARTICIPANT_TYPE=$(slot_participant_type "$SLOT")
INTEGRATION_MODE=$(slot_integration_mode "$SLOT")
note "slot $SLOT → $PARTICIPANT_TYPE via $INTEGRATION_MODE"
if [[ "$SLOT" == A || "$SLOT" == C ]]; then
  if ! confirm "Do you consent to the 30-minute usability session and aggregate activation evidence?"; then
    warn "consent is required; stop here and contact the founder"
    exit 1
  fi
else
  if ! confirm "Do you consent to an internal technical activation with aggregate evidence?"; then
    warn "consent is required; stop here"
    exit 1
  fi
fi
note "Time active human actions from the first setup instruction through the"
note "first counted call. Pause during downloads, proof generation, and provider wait."

stage "Confirm the agent-led local setup"
say "The founder grants private bundle repository access and sends your invite."
say "Slot A follows docs/onboarding/base-zk-credits-codex-first-use.md."
say "Slots B and C follow docs/onboarding/base-zk-credits-x402-agent.md."
step "The agent checks GitHub CLI authentication, installs zk-credits@$PINNED_SIDECAR_VERSION, downloads and verifies the immutable proving bundle, and runs local setup."
step "You handle GitHub sign-in, the hidden local recovery-password prompt, consent, and your own task."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is not signed in; finish gh auth login locally, then restart this wizard"
  exit 1
fi
if ! gh repo view mangekyou-labs/zk-credits-base-sepolia-v2-bundle >/dev/null 2>&1; then
  warn "the private proving-bundle repository is not readable; ask the founder to grant access"
  exit 1
fi
node_major=$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)
if [[ "$node_major" -lt 20 ]]; then warn "Node >= 20 is required"; exit 1; fi
installed_sidecar=$(npm ls -g --depth=0 --json zk-credits 2>/dev/null \
  | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{try{process.stdout.write(JSON.parse(d).dependencies?.["zk-credits"]?.version??"")}catch{process.stdout.write("")}})')
if [[ "$installed_sidecar" != "$PINNED_SIDECAR_VERSION" ]]; then
  warn "zk-credits is ${installed_sidecar:-not installed}; install exactly $PINNED_SIDECAR_VERSION from npm"
  exit 1
fi
if ! confirm "Did local setup report the pinned bundle hashes, witness, and known-root checks passed?"; then
  warn "finish local setup successfully before making any call"
  exit 1
fi
printf '  %s✓%s gh access, Node %s, and zk-credits %s verified\n' "$GREEN" "$RESET" "$(node -v)" "$installed_sidecar"

stage "Start your own agent with fresh local metrics"
say "Use one fresh local runtime for the warm-up and counted call. Make no"
say "other request during the two snapshots."
if [[ "$SLOT" == A ]]; then
  step "In a terminal run: zk-credits codex, then leave Codex waiting for a task."
elif [[ "$SLOT" == B ]]; then
  step "In a terminal run: zk-credits x402-agent"
  step "Enter the recovery password at its hidden local prompt, then leave the agent waiting for a task."
else
  step "Start your own x402 agent using createLocalX402Agent from the integration guide."
  step "Keep its authenticated loopback metrics runtime open while your own agent waits for a task."
fi
pause "Press Enter when the local agent is waiting and has made no request."
if ! METRICS_FRESH=$(sidecar_metrics_json); then
  warn "could not read authenticated loopback metrics; make sure the local agent is running"
  exit 1
fi
export METRICS_FRESH
note "fresh local snapshot captured"

stage "One discarded warm-up, then one counted own-agent call"
say "Make exactly one throwaway task through your agent. It is discarded"
say "from evidence. Wait for its complete response, then capture counters."
pause "Press Enter after exactly one warm-up exchange has completed."
if ! METRICS_AFTER_WARMUP=$(sidecar_metrics_json); then
  warn "could not read metrics after the warm-up"; exit 1
fi
export METRICS_AFTER_WARMUP
if ! node "$WIZARD_DIR/operator-evidence.mjs" warmup; then
  warn "the warm-up window is not one clean cold exchange; restart with a fresh runtime"
  exit 1
fi
printf '  %s✓%s exactly one discarded cold warm-up\n' "$GREEN" "$RESET"
say "Now make exactly one counted call using a real task you choose in your"
say "own agent. Slot C must use your own x402 integration."
pause "Press Enter after that custom task has received its complete response."
if ! METRICS_AFTER_HOT=$(sidecar_metrics_json); then
  warn "could not read metrics after the counted call"; exit 1
fi
export METRICS_AFTER_HOT
if ! node "$WIZARD_DIR/operator-evidence.mjs" hot; then
  warn "the counted window is not exactly one clean exchange; do not submit it"
  exit 1
fi
printf '  %s✓%s exactly one counted own-agent exchange\n' "$GREEN" "$RESET"

stage "Review and share redacted activation evidence"
while true; do
  ask HUMAN_ACTION_SECONDS "Active human setup seconds (pause during machine/provider waits):"
  if [[ "${HUMAN_ACTION_SECONDS:-}" =~ ^[0-9]+$ ]] && (( HUMAN_ACTION_SECONDS <= 86400 )); then break; fi
  warn "enter whole seconds from 0 to 86400"
done
HUMAN_ACTION_MS=$(( HUMAN_ACTION_SECONDS * 1000 ))
while true; do
  ask MACHINE_WAIT_SECONDS "Unattended machine/provider wait seconds (download, install, proof, and response):"
  if [[ "${MACHINE_WAIT_SECONDS:-}" =~ ^[0-9]+$ ]] && (( MACHINE_WAIT_SECONDS <= 86400 )); then break; fi
  warn "enter whole seconds from 0 to 86400"
done
MACHINE_WAIT_MS=$(( MACHINE_WAIT_SECONDS * 1000 ))
if (( HUMAN_ACTION_SECONDS > 300 )); then
  note "This exceeds the five-minute target and is recorded as friction;"
  note "it does not disqualify a valid protocol exchange."
fi
while true; do
  ask ASSISTANCE "How many times did the founder help? (0 if none):"
  if gw_require_block "$ASSISTANCE" "assistance count"; then break; fi
  warn "enter a whole number"
done
ATTEST_LOCAL='false'; ATTEST_CREDENTIAL='false'; ATTEST_NO_RECOVERY='false'; ATTEST_OWNERSHIP='false'
confirm "Did you run the agent yourself on this machine?" && ATTEST_LOCAL='true' || warn "this activation will not qualify without this"
confirm "Did your credential export and password stay on this machine?" && ATTEST_CREDENTIAL='true' || warn "this activation will not qualify without this"
confirm "Was no exceptional manual credential recovery needed?" && ATTEST_NO_RECOVERY='true' || warn "this activation will not qualify"
confirm "Are you the distinct operator assigned this slot?" && ATTEST_OWNERSHIP='true' || warn "this activation will not qualify"

BUNDLE_DIR="${ZK_CREDITS_EVIDENCE_DIR:-$PWD}"
BUNDLE="$BUNDLE_DIR/zk-credits-activation-evidence-$SLOT.json"
export SLOT PARTICIPANT_TYPE INTEGRATION_MODE ASSISTANCE HUMAN_ACTION_MS MACHINE_WAIT_MS BUNDLE
export PINNED_SIDECAR_VERSION PINNED_ADAPTER_VERSION PINNED_SHARED_VERSION PINNED_ARTIFACT_RELEASE
export ATTEST_LOCAL ATTEST_CREDENTIAL ATTEST_NO_RECOVERY ATTEST_OWNERSHIP
if ! node "$WIZARD_DIR/operator-evidence.mjs" bundle; then
  warn "the evidence bundle could not be written"; exit 1
fi
if ! gw_scan_for_secrets "$BUNDLE"; then
  warn "the bundle did not pass the local secret scan; do not send it"; exit 1
fi
say "Share only the activation evidence file with the founder. The $25 research"
say "honorarium is paid separately and is never recorded as product revenue or intent."
note "Evidence contains aggregate counters and setup duration, never task text,"
note "response content, credential, proof, nullifier, request signal, or identity join."
note "Close the local agent after evidence and metrics have been captured."

finish
