#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${ZK_CREDITS_OPERATOR_ENV:-.env.operator.local}"
WIZARD_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
if [[ -f "$WIZARD_DIR/launch-guardrails.sh" ]]; then
  # shellcheck source=scripts/launch-guardrails.sh
  source "$WIZARD_DIR/launch-guardrails.sh"
else
  printf 'Keep launch-guardrails.sh beside this wizard; it is delivered together.\n' >&2
  exit 1
fi

# Keys this wizard owns. Anything else already in the operator env is refused.
OPERATOR_KEYS=(
  ZK_CREDITS_CREDENTIAL_PATH ZK_CREDITS_CREDENTIAL_PASSWORD ZK_CREDITS_ARTIFACT_DIR
  ZK_CREDITS_HOME ZK_CREDITS_SIDECAR_PORT ZK_CREDITS_GATEWAY_URL
  ZK_CREDITS_OPERATOR_SLOT ZK_CREDITS_OPERATOR_TYPE ZK_CREDITS_INTEGRATION_MODE
  ZK_CREDITS_ONBOARDING_URL ZK_CREDITS_CALL_STARTED_AT
)

# The pinned release. Nothing else is supported, and a mismatch is a failed
# activation rather than a warning.
PINNED_SIDECAR_VERSION='0.2.0'
PINNED_ADAPTER_VERSION='0.1.0'
PINNED_SHARED_VERSION='0.1.0'
PINNED_ARTIFACT_RELEASE='private-credit-spend-bn254-dev-sepolia-v1'
PINNED_NETWORK='eip155:84532'
PINNED_DOMAIN='84532'

OPERATOR_HOME="${ZK_CREDITS_HOME:-$HOME/.zk-credits}"
TOKEN_PATH="$OPERATOR_HOME/loopback-token"

SLOT=''
PARTICIPANT_TYPE=''
INTEGRATION_MODE=''
GATEWAY_URL=''
ONBOARDING_URL=''
METRICS_BEFORE=''
CALL_STARTED_AT=0
ASSISTANCE=0

# sidecar_metrics_json prints the whole authenticated loopback snapshot.
sidecar_metrics_json() {
  local token
  [[ -f "$TOKEN_PATH" ]] || return 1
  token=$(cat "$TOKEN_PATH")
  curl -fsS --max-time 15 -H "Authorization: Bearer $token" \
    "http://127.0.0.1:${ZK_CREDITS_SIDECAR_PORT:-3210}/metrics"
}

# require_slot_* enforce the deterministic cohort assignment.
slot_participant_type() { case "$1" in A|C) printf 'coding_agent' ;; B) printf 'x402_native_agent' ;; *) return 1 ;; esac; }
slot_integration_mode() { case "$1" in A|C) printf 'openai_compatible_sidecar' ;; B) printf 'x402_zk_prepaid_adapter' ;; *) return 1 ;; esac; }

sha256_of() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  else sha256sum "$1" | awk '{print $1}'; fi
}

TOTAL_STAGES=10

banner "Operator activation: Base Sepolia x402 zk-prepaid pilot"

WIZARD_STARTED_AT=$(date +%s)

# ── Stage 1: preconditions ────────────────────────────────────────────────
stage "Preconditions: this machine owns the credential"
say "Your credential secret, its password, and your proving artifacts never"
say "leave this machine. Nothing here is shared with the project team."
note "Infrastructure material is the founder's and must not be present here:"
note "deployer or sponsor keys, the database URL, admin tokens, provider keys."
if ! gw_refuse_deployer_vars; then
  warn "unset those variables (they belong to the founder) and re-run"; exit 1
fi
if ! gw_require_ignored "$ENV_FILE"; then exit 1; fi
if ! gw_require_private_mode "$ENV_FILE"; then exit 1; fi
if ! gw_refuse_stray_keys "$ENV_FILE" "${OPERATOR_KEYS[@]}"; then exit 1; fi
printf '  %s✓%s %s is ignored and mode 600\n' "$GREEN" "$RESET" "$ENV_FILE"

# ── Stage 2: slot and local toolchain ─────────────────────────────────────
stage "Your slot and the pinned local toolchain"
say "The cohort has three slots. A and C drive an OpenAI-compatible coding"
say "agent; B is an existing x402-native agent that registers the adapter."
while true; do
  ask SLOT "Your slot (A, B, or C):"
  SLOT=$(printf '%s' "${SLOT:-}" | tr '[:lower:]' '[:upper:]')
  if [[ "$SLOT" =~ ^[ABC]$ ]]; then break; fi
  warn "the slot must be A, B, or C"
done
PARTICIPANT_TYPE=$(slot_participant_type "$SLOT")
INTEGRATION_MODE=$(slot_integration_mode "$SLOT")
note "slot $SLOT → $PARTICIPANT_TYPE via $INTEGRATION_MODE"
write_env ZK_CREDITS_OPERATOR_SLOT "$SLOT"
write_env ZK_CREDITS_OPERATOR_TYPE "$PARTICIPANT_TYPE"
write_env ZK_CREDITS_INTEGRATION_MODE "$INTEGRATION_MODE"

say "Now check the pinned versions. Mixing versions fails at settlement."
node_major=$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)
if [[ "$node_major" -lt 20 ]]; then warn "Node >= 20 is required"; exit 1; fi
printf '  %s✓%s Node %s\n' "$GREEN" "$RESET" "$(node -v)"
installed_sidecar=$(npm ls -g --depth=0 --json zk-credits 2>/dev/null \
  | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{try{process.stdout.write(JSON.parse(d).dependencies?.["zk-credits"]?.version??"")}catch{process.stdout.write("")}})')
if [[ "$installed_sidecar" != "$PINNED_SIDECAR_VERSION" ]]; then
  warn "zk-credits is ${installed_sidecar:-not installed}; the pilot requires $PINNED_SIDECAR_VERSION"
  warn "  npm install --global zk-credits@$PINNED_SIDECAR_VERSION"
  exit 1
fi
printf '  %s✓%s zk-credits %s\n' "$GREEN" "$RESET" "$installed_sidecar"

# ── Stage 3: artifact directory and hashes ────────────────────────────────
stage "Pinned proving artifacts"
say "Set ZK_CREDITS_ARTIFACT_DIR to the directory delivered through your invite."
ask ZK_CREDITS_ARTIFACT_DIR "Path to the proving bundle:"
if ! gw_require_match "$ZK_CREDITS_ARTIFACT_DIR" '^/.+' "ZK_CREDITS_ARTIFACT_DIR"; then exit 1; fi
if [[ ! -d "$ZK_CREDITS_ARTIFACT_DIR" ]]; then warn "no such directory"; exit 1; fi
write_env ZK_CREDITS_ARTIFACT_DIR "$ZK_CREDITS_ARTIFACT_DIR"

MANIFEST="$(dirname "$WIZARD_DIR")/packages/zk-credits-sidecar/circuits/manifest.json"
if [[ ! -f "$MANIFEST" ]]; then
  MANIFEST=$(npm root -g)/zk-credits/circuits/manifest.json
fi
if [[ ! -f "$MANIFEST" ]]; then
  warn "could not find the pinned manifest; pass the bundle that shipped with your invite"
  ask MANIFEST "Path to manifest.json:"
  if ! gw_require_match "$MANIFEST" '^/.+' "manifest path"; then exit 1; fi
fi

# Compare every delivered artifact against the manifest digest.
mismatch=0
while IFS=$'\t' read -r file expected; do
  [[ -z "$file" ]] && continue
  actual=$(sha256_of "$ZK_CREDITS_ARTIFACT_DIR/$file" 2>/dev/null || echo '')
  if [[ "$actual" != "$expected" ]]; then
    warn "$file does not match the pinned digest"
    mismatch=1
  else
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$file"
  fi
done < <(node -e '
  const fs = require("fs");
  const m = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  for (const a of m.artifacts ?? []) console.log(`${a.file}\t${a.sha256}`);
' "$MANIFEST")
if [[ "$mismatch" -ne 0 ]]; then
  warn "a mismatched artifact is a proof failure; the sidecar refuses to prove"
  exit 1
fi

# ── Stage 4: gateway readiness and network values ─────────────────────────
stage "Gateway readiness and the pinned Base network"
say "The sidecar only ever talks to the project gateway, and only on Base"
say "Sepolia (eip155:84532)."
ask ZK_CREDITS_GATEWAY_URL "Gateway base URL (https://…):"
if ! gw_require_https_url "$ZK_CREDITS_GATEWAY_URL" "ZK_CREDITS_GATEWAY_URL"; then exit 1; fi
GATEWAY_URL="$ZK_CREDITS_GATEWAY_URL"
write_env ZK_CREDITS_GATEWAY_URL "$GATEWAY_URL"

note "A free instance suspends, so the first request may take a moment."
for attempt in $(seq 1 12); do
  if curl -fsS --max-time 30 "$GATEWAY_URL/health" >/dev/null 2>&1; then break; fi
  if [[ "$attempt" -eq 12 ]]; then warn "the gateway did not become live"; exit 1; fi
  note "  attempt $attempt/12; retrying in 5s"
  sleep 5
done
printf '  %s✓%s /health live\n' "$GREEN" "$RESET"

supported=$(curl -fsS --max-time 30 "$GATEWAY_URL/x402/facilitator/supported")
for expect in 'zk-prepaid' "$PINNED_NETWORK" "$PINNED_DOMAIN"; do
  if ! printf '%s' "$supported" | grep -q "$expect"; then
    warn "the gateway does not advertise $expect"; exit 1
  fi
done
printf '  %s✓%s gateway advertises zk-prepaid on %s (domain %s)\n' "$GREEN" "$RESET" "$PINNED_NETWORK" "$PINNED_DOMAIN"

# ── Stage 5: onboarding and invite redemption ─────────────────────────────
stage "GitHub onboarding: redeem your single-use invite"
say "Your invite is bound to one GitHub account and can be redeemed once."
say "You will create the credential and back it up in your browser. The"
say "credential secret and its password are never sent to the project."
ask ONBOARDING_URL "Onboarding URL from your invite:"
if ! gw_require_https_url "$ONBOARDING_URL" "onboarding URL"; then exit 1; fi
write_env ZK_CREDITS_ONBOARDING_URL "$ONBOARDING_URL"
open_url "$ONBOARDING_URL"
step "Sign in with the GitHub account the invite names."
step "Redeem the invite."
step "Create the credential, then download the encrypted backup."
step "Store the backup and its password on this machine only."
while true; do
  ask ZK_CREDITS_CREDENTIAL_PATH "Path to the downloaded credential backup:"
  if gw_require_match "$ZK_CREDITS_CREDENTIAL_PATH" '^/.+' "credential path" && [[ -f "$ZK_CREDITS_CREDENTIAL_PATH" ]]; then break; fi
  warn "that path does not exist yet"
done
chmod 600 "$ZK_CREDITS_CREDENTIAL_PATH" 2>/dev/null || true
write_env ZK_CREDITS_CREDENTIAL_PATH "$ZK_CREDITS_CREDENTIAL_PATH"
note "Do not paste the password here or share it. The sidecar prompts locally."

# ── Stage 6: fresh snapshot and the discarded warm-up ─────────────────────
stage "Fresh sidecar snapshot, then one discarded warm-up"
say "The first proof in a process compiles the circuit and is much slower."
say "Your activation is measured as deltas between counter snapshots, so the"
say "warm-up is proved rather than assumed: exactly one cold exchange here,"
say "and exactly one counted exchange after it."
step "In another terminal, start the sidecar:"
note "  eval \"\$(zk-credits env)\" ; zk-credits serve"
step "Make no call yet. This stage reads the counters first."
pause "Press Enter once the sidecar is running and has served nothing."

if ! METRICS_FRESH=$(sidecar_metrics_json); then
  warn "could not read $TOKEN_PATH; is the sidecar running?"
  warn "start it with: zk-credits serve"
  exit 1
fi
export METRICS_FRESH
note "fresh snapshot recorded"

step "Now run one throwaway call through your agent."
pause "Press Enter once the warm-up call has finished."

if ! METRICS_AFTER_WARMUP=$(sidecar_metrics_json); then
  warn "could not read the counters after the warm-up"
  exit 1
fi
export METRICS_AFTER_WARMUP
note "The warm-up may have consumed a test credit. That is expected and is"
note "never part of your evidence."

# Checked here as well as by the founder, so a retried or shared warm-up is
# caught while you can still discard it instead of after you have sent it.
if ! node "$WIZARD_DIR/operator-evidence.mjs" warmup; then
  warn "the warm-up is not one clean cold exchange; restart the sidecar and retry"
  exit 1
fi
printf '  %s✓%s the warm-up window holds exactly one clean cold exchange\n' "$GREEN" "$RESET"

# ── Stage 7: activation baseline ──────────────────────────────────────────
stage "Baseline metrics (the snapshot taken after the warm-up)"
say "This is the activation baseline. Everything after it is your counted"
say "exchange, and nothing before it can be counted."
note "baseline recorded"
CALL_STARTED_AT=$(date +%s)

# ── Stage 8: the real activation call ─────────────────────────────────────
stage "Your real call, from your existing agent loop"
say "Now make one real call the way you normally work: your own agent, your"
say "own prompt, your own machine. Not a script and not a retry of a retry."
if [[ "$SLOT" == "B" ]]; then
  step "Register @zk-credits/x402-zk-prepaid@$PINNED_ADAPTER_VERSION in your agent."
  step "Then run one normal task through it."
else
  step "Run one normal task through your coding agent."
fi
pause "Press Enter once that call has completed."

# ── Stage 9: compute the deltas and write the bundle ──────────────────────
stage "Redacted evidence bundle"
say "Only aggregate counters leave this machine. No prompt, response, proof,"
say "public signal, nullifier, credential, or invite token is ever recorded."
while true; do
  ask ASSISTANCE "How many times did the founder help you? (0 if none):"
  if gw_require_block "$ASSISTANCE" "assistance count"; then break; fi
  warn "give a whole number"
done

ATTEST_LOCAL='false'; ATTEST_CREDENTIAL='false'; ATTEST_NO_RECOVERY='false'; ATTEST_OWNERSHIP='false'
confirm "Did you run the agent yourself, on this machine?" && ATTEST_LOCAL='true' || warn "note: this will fail qualification"
confirm "Did your credential and password stay on this machine?" && ATTEST_CREDENTIAL='true' || warn "note: this will fail qualification"
confirm "Was any manual recovery needed for the credential?" && warn "manual recovery means this activation cannot qualify" || ATTEST_NO_RECOVERY='true'
confirm "Is this slot yours alone, separate from every other operator?" && ATTEST_OWNERSHIP='true' || warn "note: this will fail qualification"

BUNDLE_DIR="${ZK_CREDITS_EVIDENCE_DIR:-$PWD}"
BUNDLE="$BUNDLE_DIR/zk-credits-activation-evidence-$SLOT.json"
# Onboarding time is wall-clock from the first stage to the real call.
ONBOARDING_MS=$(( (CALL_STARTED_AT - WIZARD_STARTED_AT) * 1000 ))
if [[ "$ONBOARDING_MS" -lt 0 ]]; then ONBOARDING_MS=0; fi

# The counted window is measured the same way the warm-up was: a second
# snapshot, then a delta. A contaminated window is refused here rather than
# sent to the founder.
if ! METRICS_AFTER_HOT=$(sidecar_metrics_json); then
  warn "could not read the counters after your call"; exit 1
fi
export METRICS_AFTER_HOT
if ! node "$WIZARD_DIR/operator-evidence.mjs" hot; then
  warn "your counted exchange is not one clean exchange"
  warn "the most common cause is a retry, or another call sharing this sidecar"
  exit 1
fi
printf '  %s✓%s the counted window holds exactly one clean exchange\n' "$GREEN" "$RESET"

export SLOT PARTICIPANT_TYPE INTEGRATION_MODE ASSISTANCE ONBOARDING_MS BUNDLE
export PINNED_SIDECAR_VERSION PINNED_ADAPTER_VERSION PINNED_SHARED_VERSION
export PINNED_ARTIFACT_RELEASE
export ATTEST_LOCAL ATTEST_CREDENTIAL ATTEST_NO_RECOVERY ATTEST_OWNERSHIP

if ! node "$WIZARD_DIR/operator-evidence.mjs" bundle; then
  warn "the evidence bundle could not be written"; exit 1
fi

# ── Stage 10: final scan and hand-off ─────────────────────────────────────
stage "Final scan and hand-off"
if ! gw_scan_for_secrets "$BUNDLE"; then
  warn "the bundle is not clean; do not send it"; exit 1
fi
printf '  %s✓%s the bundle carries no key, token, connection string, or address\n' "$GREEN" "$RESET"
say "Send only this file to the founder. Nothing else leaves this machine."
note "The founder validates it with: npm run activation:evidence -- --slot $SLOT --file <bundle>"
note "Keep your credential, its password, and your artifacts here. The project"
note "team must never handle them."

finish
